# Generated by Django 6.0 — SNOW-330 location_source and raw GPS fix fields.

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add location_source, gps_latitude, and gps_longitude to FieldObservation.

    ``location_source`` is non-null. All existing rows pre-date the feature and
    were recorded from a GPS fix, so the one-off default ``"GPS"`` is used with
    ``preserve_default=False`` to backfill the column without a data migration
    command.

    ``gps_latitude`` and ``gps_longitude`` are nullable (null when the
    subscriber used the MANUAL path and no device fix was obtained).
    """

    dependencies = [
        ("observations", "0002_seed_field_observations_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldobservation",
            name="location_source",
            field=models.CharField(
                choices=[
                    ("GPS", "GPS"),
                    ("GPS_REFINED", "GPS (refined)"),
                    ("MANUAL", "Manual"),
                ],
                default="GPS",
                help_text=(
                    "How the report coordinate was determined: GPS (raw fix), "
                    "GPS_REFINED (fix then pin drag), or MANUAL (pin only, no fix)."
                ),
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fieldobservation",
            name="gps_latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text=(
                    "WGS-84 latitude of the raw device GPS fix at report time. "
                    "Null when location_source is MANUAL (no GPS fix obtained)."
                ),
            ),
        ),
        migrations.AddField(
            model_name="fieldobservation",
            name="gps_longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text=(
                    "WGS-84 longitude of the raw device GPS fix at report time. "
                    "Null when location_source is MANUAL (no GPS fix obtained)."
                ),
            ),
        ),
    ]
