# Generated by Django 6.1.1 on 2026-09-04 17:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0004_location_short_id"),
        ("routes", "0004_routeshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        help_text="The day of the trip, as a wall-clock date at the meeting point. Never converted between timezones."
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="The meeting time, as wall-clock at the meeting point. Never converted between timezones — see the class docstring."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The organiser's label for the trip. May be blank, in which case surfaces fall back to route_name.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The organiser's note to the group — what to bring, where to park, who has the rope. Plain text, auto-escaped on render.",
                    ),
                ),
                (
                    "points",
                    models.JSONField(
                        help_text="Snapshot of the route's simplified track as [[lon, lat, ele], …] in GeoJSON axis order, copied at creation and never re-read from the route."
                    ),
                ),
                (
                    "bounds",
                    models.JSONField(
                        help_text="Snapshot of the route's GeoJSON bbox: [min_lon, min_lat, max_lon, max_lat]."
                    ),
                ),
                (
                    "distance_m",
                    models.FloatField(
                        help_text="Snapshot of the route's length in metres."
                    ),
                ),
                (
                    "ascent_m",
                    models.FloatField(
                        blank=True,
                        help_text="Snapshot of the route's total climb in metres. Null — not zero — when the source route had no elevation data at all.",
                        null=True,
                    ),
                ),
                (
                    "descent_m",
                    models.FloatField(
                        blank=True,
                        help_text="Snapshot of the route's total drop in metres, as a positive magnitude. Null on the same condition as ascent_m.",
                        null=True,
                    ),
                ),
                (
                    "point_count",
                    models.PositiveIntegerField(
                        help_text="Number of coordinates stored in points."
                    ),
                ),
                (
                    "route_name",
                    models.CharField(
                        blank=True,
                        help_text="The source route's label at the moment the trip was created. The fallback for a trip with no name of its own, and the seed for a saved copy's name (SNOW-824).",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The organiser — the account that created this trip. Organiser-ness is derived from this column, never stored a second time on the participant row.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting_point",
                    models.ForeignKey(
                        help_text="Where the group meets. A Location minted for this trip alone, carrying no name and no kind. PROTECT — see the class docstring for why the orphan sweep depends on it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="locations.location",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="The route this trip was planned from. PROVENANCE ONLY — no rendering path follows it; the snapshot fields below are what every surface reads. Nulled when the organiser deletes the route, which leaves the trip intact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TripParticipant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this account joined. The organiser's row carries the moment the trip was created.",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="The trip this participation is on. CASCADE — deleting a trip removes it for everyone, which is what the delete confirmation says it does.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The account going on the trip.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "user"), name="unique_trip_participant"
                    )
                ],
            },
        ),
    ]
