# Generated by Django 6.1.1 on 2026-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="share_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the link stops working. Derived from the trip's own DATE plus settings.TRIP_SHARE_MAX_AGE_DAYS, never from the mint time — see share_is_live.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="share_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="URL-safe random token used in the /trips/s/<token>/ short URL. Null until the organiser shares the trip, and nulled again when they revoke it.",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
