# Generated by Django 6.1.1 on 2026-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0002_trip_share_expires_at_trip_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="slope_samples",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of the source route's terrain record, in the shape Route.slope_samples stores (see apps/routes/services/slope_segments.py). Copied at creation and never re-read, like the geometry beside it — the ground under a track is as static as the track. Null means NEVER SAMPLED, which is not the same fact as a segment carrying an unknown reason.",
                null=True,
            ),
        ),
    ]
