# Generated by Django 5.2.13 on 2026-04-10 10:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "triggered_by",
                    models.CharField(
                        default="unknown",
                        help_text="Who or what triggered this run (e.g. 'scheduler', 'backfill', 'manual').",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_id",
                    models.CharField(
                        db_index=True,
                        help_text="SLF region identifier, e.g. 'CH-4115'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["region_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bulletin_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full CAAML bulletin wrapped in a GeoJSON Feature envelope.",
                    ),
                ),
                ("issued_at", models.DateTimeField(db_index=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("next_update", models.DateTimeField(blank=True, null=True)),
                ("lang", models.CharField(default="en", max_length=8)),
                ("unscheduled", models.BooleanField(default=False)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulletins",
                        to="pipeline.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegionBulletin",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_name_at_time",
                    models.CharField(
                        blank=True,
                        help_text="Region name as it appeared in this bulletin.",
                        max_length=255,
                    ),
                ),
                (
                    "bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_links",
                        to="pipeline.bulletin",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletin_links",
                        to="pipeline.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region__region_id"],
                "abstract": False,
                "unique_together": {("bulletin", "region")},
            },
        ),
        migrations.AddField(
            model_name="bulletin",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="bulletins",
                through="pipeline.RegionBulletin",
                to="pipeline.region",
            ),
        ),
    ]
