# Generated by Django 5.2.13 on 2026-04-13 14:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resort",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternative or marketing name for the resort.",
                        max_length=255,
                    ),
                ),
                (
                    "canton",
                    models.CharField(
                        help_text="Swiss canton abbreviation, e.g. 'VS', 'GR'.",
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resorts",
                        to="pipeline.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
