# Generated by Django 5.2.13 on 2026-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0002_add_resort_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="boundary",
            field=models.JSONField(
                blank=True,
                help_text='Region boundary as a GeoJSON Polygon geometry object ({"type": "Polygon", "coordinates": [...]}). Stored as JSON rather than a PostGIS geometry type.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="centre",
            field=models.JSONField(
                blank=True,
                help_text='Geographic centre of the region as {"lon": float, "lat": float}. Stored as JSON; uses WGS 84 coordinates.',
                null=True,
            ),
        ),
    ]
