# Generated by Django 5.2.13 on 2026-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0003_region_boundary_region_centre"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="render_model",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Versioned, presentation-ready view of the bulletin built from raw_data. Shape: {version, danger, traits, fallback_key_message, snowpack_structure}. Rebuilt automatically by upsert_bulletin and on demand by rebuild_render_models.",
            ),
        ),
        migrations.AddField(
            model_name="bulletin",
            name="render_model_version",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Version of the render_model schema. 0 means not yet built.",
            ),
        ),
    ]
