# Generated by Django 5.2.13 on 2026-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0004_bulletin_render_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinerun",
            name="records_failed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of bulletins whose render model could not be built (stored with version=0 error sentinel).",
            ),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="render_model",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Versioned, presentation-ready view of the bulletin built from raw_data. Shape: {version, danger, traits, fallback_key_message, snowpack_structure}. Rebuilt by upsert_bulletin and on demand by rebuild_render_models.",
            ),
        ),
    ]
