# Generated by Django 5.2.13 on 2026-04-16 19:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0005_pipelinerun_records_failed"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionDayRating",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "min_rating",
                    models.CharField(
                        choices=[
                            ("no_rating", "No rating"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("considerable", "Considerable"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        default="no_rating",
                        help_text=(
                            "Lowest danger rating across all qualifying bulletins for this day. "
                            "Equals max_rating on uniform days; differs on variable days."
                        ),
                        max_length=16,
                    ),
                ),
                (
                    "min_subdivision",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "Subdivision suffix ('+', '-', '=') from the bulletin that gave "
                            "min_rating (latest valid_from on ties), or blank."
                        ),
                        max_length=2,
                    ),
                ),
                (
                    "max_rating",
                    models.CharField(
                        choices=[
                            ("no_rating", "No rating"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("considerable", "Considerable"),
                            ("high", "High"),
                            ("very_high", "Very high"),
                        ],
                        default="no_rating",
                        max_length=16,
                    ),
                ),
                (
                    "max_subdivision",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subdivision suffix ('+', '-', '=') from the source bulletin, or blank.",
                        max_length=8,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="DAY_RATING_VERSION at the time this row was computed.",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_ratings",
                        to="pipeline.region",
                    ),
                ),
                (
                    "source_bulletin",
                    models.ForeignKey(
                        blank=True,
                        help_text="The bulletin that produced max_rating.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_ratings",
                        to="pipeline.bulletin",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "region__region_id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["region", "date"], name="pipeline_re_region__fa9668_idx"
                    )
                ],
                "unique_together": {("region", "date")},
            },
        ),
    ]
