# Generated by Django 5.2.13 on 2026-04-24 08:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0010_single_bulletin_day_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="EawsMajorRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="EAWS L1 prefix, e.g. 'CH-4'.",
                        max_length=4,
                        unique=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        help_text="ISO-3166-1 alpha-2 country code, e.g. 'CH'.",
                        max_length=2,
                    ),
                ),
                (
                    "name_native",
                    models.CharField(
                        help_text="Region name in the locally dominant language (German / French / Italian for Switzerland).",
                        max_length=100,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="English name where SLF publishes one; blank otherwise.",
                        max_length=100,
                    ),
                ),
                (
                    "centre",
                    models.JSONField(
                        blank=True,
                        help_text='Derived geographic centre as {"lon": float, "lat": float}. Computed by refresh_eaws_fixtures from the union of L4 children.',
                        null=True,
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        help_text="Derived bounding box as [min_lon, min_lat, max_lon, max_lat]. Computed by refresh_eaws_fixtures from the union of L4 children.",
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        help_text="Derived outer boundary as a GeoJSON Polygon or MultiPolygon. Computed by refresh_eaws_fixtures from the union of L4 children.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "EAWS major region",
                "verbose_name_plural": "EAWS major regions",
                "ordering": ["prefix"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EawsSubRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="EAWS L2 prefix, e.g. 'CH-41'.",
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "name_native",
                    models.CharField(
                        help_text="Region name in the locally dominant language (German / French / Italian for Switzerland).",
                        max_length=100,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="English name where SLF publishes one; blank otherwise.",
                        max_length=100,
                    ),
                ),
                ("centre", models.JSONField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("boundary", models.JSONField(blank=True, null=True)),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subregions",
                        to="pipeline.eawsmajorregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "EAWS sub-region",
                "verbose_name_plural": "EAWS sub-regions",
                "ordering": ["prefix"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="region",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent L2 sub-region. Populated from ``region_id[:5]`` in the fixture; migration 0012 back-fills historical rows.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="pipeline.eawssubregion",
            ),
        ),
    ]
