# Generated by Django 5.2.13 on 2026-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0013_require_subregion"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="geocode_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resort",
            name="geocode_source",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("auto", "Auto"), ("import", "Import")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="geocoded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resort",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resort",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resort",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
