# Generated by Django 5.2.13 on 2026-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipeline", "0014_resort_geocoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="neighbours",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic neighbours — other regions whose polygons share a border with this one. Computed at fixture-build time from the boundary geometry (see scripts/build_regions_fixture.py); not maintained at runtime.",
                to="pipeline.region",
            ),
        ),
    ]
