# Generated by Django 6.0.7 on 2026-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_passkey_fk_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="inactive_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the push service reports 410 Gone. Null while live.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="mechanism",
            field=models.CharField(
                choices=[
                    ("sw", "Service worker"),
                    ("declarative", "Declarative Web Push"),
                ],
                default="sw",
                help_text="Which browser API produced this subscription (sw or declarative).",
                max_length=16,
            ),
        ),
    ]
