# Generated by Django 6.0.7 on 2026-07-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                help_text="A new email address awaiting verification (SNOW-433). The account keeps its current (verified) address until this one is confirmed.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="pending_email_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pending email change was requested.",
                null=True,
            ),
        ),
    ]
