# Generated by Django 6.0.7 on 2026-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_drop_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="mechanism",
            field=models.CharField(
                choices=[
                    ("SW", "Service worker"),
                    ("DECLARATIVE", "Declarative Web Push"),
                ],
                default="SW",
                help_text="Which browser API produced this subscription (SW or DECLARATIVE).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="geo_match_kind",
            field=models.CharField(
                choices=[
                    ("IN_REGION", "In region"),
                    ("IN_NEIGHBOUR", "In neighbouring region"),
                    ("ELSEWHERE", "Elsewhere"),
                    ("UNKNOWN", "Unknown"),
                ],
                db_index=True,
                default="UNKNOWN",
                help_text="How the account's geolocation (from subscribed_via) relates to the subscribed region at sign-up time. Frozen on INSERT; never updated. Raw geo fields live on subscribed_via (RequestLog).",
                max_length=16,
            ),
        ),
    ]
