[tox]
no_package = True
envlist =
    fmt, lint, mypy,
    django-checks,
    test

[testenv:test]
description = Run tests with coverage
deps =
    coverage
    pytest
    pytest-cov
    pytest-django
    Django
    django-htmx
    python-decouple
    requests
    factory-boy
    PyJWT
    freezegun
    pyyaml
    bleach
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    pytest --cov=pipeline --cov=public --cov=subscriptions --cov=config tests/

[testenv:django-checks]
description = Django system checks and missing migrations
deps =
    Django
    django-htmx
    python-decouple
    requests
    PyJWT
    pyyaml
    bleach
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    python manage.py check --fail-level WARNING
    python manage.py makemigrations --dry-run --check --verbosity 3
    python manage.py compilemessages

[testenv:fmt]
description = Python source code formatting (ruff format)
deps =
    ruff
commands =
    ruff format --check .

[testenv:lint]
description = Python source code linting and import sorting (ruff)
deps =
    ruff
commands =
    ruff check .

[testenv:mypy]
description = Python source code type hints (mypy)
deps =
    mypy
    Django
    django-htmx
    django-stubs
    python-decouple
    requests
    types-requests
    PyJWT
    factory-boy
    bleach
    types-bleach
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    mypy pipeline/ public/ subscriptions/ tests/ config/
