[tox]
no_package = True
envlist =
    fmt, lint, mypy,
    django-checks,
    test

[testenv:test]
description = Run tests with coverage
deps =
    coverage
    pytest
    pytest-cov
    pytest-django
    Django
    django-htmx
    python-decouple
    requests
    factory-boy
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    pytest --cov=pipeline --verbose tests/

[testenv:django-checks]
description = Django system checks and missing migrations
deps =
    Django
    django-htmx
    python-decouple
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    python manage.py check --fail-level WARNING
    python manage.py makemigrations --dry-run --check --verbosity 3

[testenv:fmt]
description = Python source code formatting (black, isort)
deps =
    black
    isort
commands =
    black --check pipeline tests
    isort --check-only pipeline tests

[testenv:lint]
description = Python source code linting (ruff)
deps =
    ruff
commands =
    ruff check pipeline tests

[testenv:mypy]
description = Python source code type hints (mypy)
deps =
    mypy
    Django
    django-htmx
    django-stubs
    python-decouple
    requests
    types-requests
setenv =
    DJANGO_SETTINGS_MODULE = config.settings.development
commands =
    mypy pipeline/
