# Generated by Django 6.0.7 on 2026-07-18 15:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bulletins", "0008_forecastpoint"),
        ("regions", "0007_regionalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional user-supplied label for this favourite.",
                        max_length=100,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="WGS-84 latitude of the saved pin."),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="WGS-84 longitude of the saved pin."),
                ),
                (
                    "elevation",
                    models.FloatField(
                        help_text="Elevation in metres, taken from the resolved ForecastPoint's sampling elevation."
                    ),
                ),
                (
                    "forecast_point",
                    models.ForeignKey(
                        help_text="Shared ForecastPoint this pin's coordinates resolved to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="favourites",
                        to="bulletins.forecastpoint",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Best-effort MicroRegion resolved from the pin location. Null when the point cannot be matched to a known boundary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favourites",
                        to="regions.microregion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved this favourite.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
