# Generated by Django 6.0.7 on 2026-07-23 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0011_alter_bulletin_render_model"),
        ("favourites", "0003_favourite_favourite_latitude_within_wgs84_and_more"),
        ("regions", "0007_regionalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="resort",
            field=models.ForeignKey(
                blank=True,
                help_text="The public Resort this favourite was created from, when created via the resort-pin popup rather than a dropped pin.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favourites",
                to="regions.resort",
            ),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resort__isnull", False)),
                fields=("user", "resort"),
                name="favourite_unique_user_resort",
            ),
        ),
    ]
