# Generated by Django 6.0.5 on 2026-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0003_bulletinshareclick_request_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="regiondayrating",
            name="am_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_rating", "No rating"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("considerable", "Considerable"),
                    ("high", "High"),
                    ("very_high", "Very high"),
                ],
                help_text="Danger rating for the morning (all_day/earlier) period on split days. Null on uniform days.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="regiondayrating",
            name="am_subdivision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subdivision suffix for the AM period, or blank.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="regiondayrating",
            name="pm_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_rating", "No rating"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("considerable", "Considerable"),
                    ("high", "High"),
                    ("very_high", "Very high"),
                ],
                help_text="Danger rating for the afternoon (later) period on split days. Null on uniform days.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="regiondayrating",
            name="pm_subdivision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subdivision suffix for the PM period, or blank.",
                max_length=8,
            ),
        ),
    ]
