# Generated by Django 6.0.5 on 2026-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0004_region_day_rating_am_pm"),
    ]

    operations = [
        migrations.AddField(
            model_name="regiondayrating",
            name="bands",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Elevation-band breakdown for ALBINA bulletins. Each entry is {'band_id': str, 'label': str, 'rating_key': str, 'time_period': str}. None for SLF, MeteoFrance, and no-rating rows.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="regiondayrating",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slf", "SLF (Switzerland)"),
                    ("albina", "ALBINA (Austria/South Tyrol/Trentino)"),
                    ("meteofrance", "Météo-France (France)"),
                ],
                default="",
                help_text="Originating bulletin source (e.g. 'slf', 'albina', 'meteofrance'). Blank for no-rating rows where source_bulletin is None.",
                max_length=16,
            ),
        ),
    ]
