# Generated by Django 6.0.6 on 2026-06-16 17:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0006_bulletin_pdf_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinGrouping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_date",
                    models.DateField(
                        db_index=True,
                        help_text="Calendar date this bulletin is forecasting, as determined by the same morning/evening boundary rule used by the day-rating service.",
                    ),
                ),
                (
                    "boundary",
                    models.JSONField(
                        help_text="Dissolved GeoJSON geometry (Polygon or MultiPolygon) covering all micro-regions linked to the bulletin that carry a boundary."
                    ),
                ),
                (
                    "countries",
                    models.JSONField(
                        default=list,
                        help_text="Sorted list of ISO-2 country codes touched by the bulletin's regions (e.g. ['AT', 'IT'] for an ALBINA cross-border bulletin).",
                    ),
                ),
                (
                    "bulletin",
                    models.OneToOneField(
                        help_text="The bulletin whose linked micro-regions were dissolved.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grouping",
                        to="bulletins.bulletin",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date"],
                "abstract": False,
            },
        ),
    ]
