# Generated by Django 6.0.7 on 2026-07-18 13:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0007_bulletingrouping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastPoint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lat_cell",
                    models.IntegerField(
                        help_text="floor(latitude / LAT_CELL_SIZE) — see forecast_points.py."
                    ),
                ),
                (
                    "lon_cell",
                    models.IntegerField(
                        help_text="floor(longitude / LON_CELL_SIZE) — see forecast_points.py."
                    ),
                ),
                (
                    "elevation_band",
                    models.IntegerField(
                        help_text="floor(elevation / ELEVATION_BAND_SIZE) — see forecast_points.py."
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Representative latitude of the pin that resolved to this point."
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Representative longitude of the pin that resolved to this point."
                    ),
                ),
                (
                    "elevation",
                    models.FloatField(
                        help_text="Representative elevation in metres, from the Open-Meteo lookup."
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("lat_cell", "lon_cell", "elevation_band")},
            },
        ),
    ]
