# Generated by Django 6.0.7 on 2026-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0009_forecastpointweather"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastpointweather",
            name="freezing_level_height",
            field=models.FloatField(
                blank=True,
                help_text="Daily maximum freezing level height, in metres. Open-Meteo has no daily freezing-level aggregate — this is derived as the maximum of the hourly freezing_level_height values for the day.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="forecastpointweather",
            name="hourly_series",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Near-term hourly detail for this day, as a list of dicts with keys time, temperature_2m, snowfall, precipitation, wind_speed_10m, wind_gusts_10m, freezing_level_height. Only populated for the first POINT_HOURLY_DAYS rows of a fetch; None beyond, to keep the JSON payload bounded.",
                null=True,
            ),
        ),
    ]
