# Generated by Django 6.0.7 on 2026-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0011_alter_bulletin_render_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="target_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Calendar date this bulletin is forecasting, as determined by target_day_for_valid_from() from valid_from. Populated by upsert_bulletin at ingest time and back-filled by the backfill_bulletin_target_dates management command.",
                null=True,
            ),
        ),
    ]
