# Generated by Django 6.0.7 on 2026-07-31 15:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0012_bulletin_target_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastPointWeatherHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this row was last written (updated on every upsert).",
                    ),
                ),
                (
                    "valid_for_date",
                    models.DateField(
                        db_index=True,
                        help_text="The calendar date this forecast applies to.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateField(
                        help_text="The date this view of valid_for_date was fetched — the anchor date of the run that produced it."
                    ),
                ),
                (
                    "lead_days",
                    models.SmallIntegerField(
                        help_text="valid_for_date - issued_date, in days. Denormalised from the two dates so that querying one lead time across many days (e.g. every three-day-out forecast) is indexable. Signed: a response whose first day precedes the run anchor yields a negative value, which is recorded rather than clamped."
                    ),
                ),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(
                        help_text="WMO weather interpretation code (0–99)."
                    ),
                ),
                (
                    "temperature_2m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "temperature_2m_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "precipitation_sum",
                    models.FloatField(
                        blank=True,
                        help_text="Total daily precipitation (rain + showers + snow), in mm.",
                        null=True,
                    ),
                ),
                (
                    "snowfall_sum",
                    models.FloatField(
                        blank=True, help_text="Total daily snowfall, in cm.", null=True
                    ),
                ),
                (
                    "wind_speed_10m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily wind speed at 10m, in km/h.",
                        null=True,
                    ),
                ),
                (
                    "freezing_level_height",
                    models.FloatField(
                        blank=True,
                        help_text="Daily maximum freezing level height, in metres.",
                        null=True,
                    ),
                ),
                (
                    "forecast_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_history",
                        to="bulletins.forecastpoint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "forecast point weather history",
                "ordering": ["-valid_for_date", "issued_date"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["forecast_point", "valid_for_date"],
                        name="bulletins_f_forecas_95f2d5_idx",
                    ),
                    models.Index(
                        fields=["valid_for_date", "lead_days"],
                        name="bulletins_f_valid_f_dd24eb_idx",
                    ),
                ],
                "unique_together": {
                    ("forecast_point", "valid_for_date", "issued_date")
                },
            },
        ),
    ]
