# Generated by Django 6.0.7 on 2026-07-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0013_forecastpointweatherhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slf", "SLF (Switzerland)"),
                    ("albina", "ALBINA (Austria/South Tyrol/Trentino)"),
                    ("meteofrance", "Météo-France (France)"),
                ],
                db_index=True,
                help_text="Provider this bulletin was ingested from, detected from raw_data.customData by detect_source. Blank only for rows predating the field and not yet covered by backfill_bulletin_source, or whose customData carries no known source marker.",
                max_length=16,
            ),
        ),
    ]
