# Generated by Django 6.0.7 on 2026-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0014_bulletin_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathersnapshot",
            name="snowfall_sum",
            field=models.FloatField(
                blank=True, help_text="Total daily snowfall, in cm.", null=True
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="temperature_2m_max",
            field=models.FloatField(
                blank=True,
                help_text="Maximum daily air temperature at 2m, in °C.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="temperature_2m_min",
            field=models.FloatField(
                blank=True,
                help_text="Minimum daily air temperature at 2m, in °C.",
                null=True,
            ),
        ),
    ]
