# Generated by Django 6.0.7 on 2026-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0014_bulletin_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
