# Generated by Django 6.0.7 on 2026-08-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0015_uppercase_pipelinerun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SLF", "SLF (Switzerland)"),
                    ("ALBINA", "ALBINA (Austria/South Tyrol/Trentino)"),
                    ("METEOFRANCE", "Météo-France (France)"),
                ],
                db_index=True,
                help_text="Provider this bulletin was ingested from, detected from raw_data.customData by detect_source. Blank only for rows predating the field and not yet covered by backfill_bulletin_source, or whose customData carries no known source marker.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="regiondayrating",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SLF", "SLF (Switzerland)"),
                    ("ALBINA", "ALBINA (Austria/South Tyrol/Trentino)"),
                    ("METEOFRANCE", "Météo-France (France)"),
                ],
                default="",
                help_text="Originating bulletin source (e.g. 'SLF', 'ALBINA', 'METEOFRANCE'). Blank for no-rating rows where source_bulletin is None.",
                max_length=16,
            ),
        ),
    ]
