# Generated by Django 6.0.7 on 2026-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    # SNOW-652: renumbered from 0015 and re-pointed at 0016. SNOW-571 and
    # SNOW-582 both branched this off 0014_bulletin_source and merged
    # without either being re-tested against the other, leaving two leaf
    # nodes and a migrate that refused to run at all. Chained here instead,
    # so the graph has one leaf. Safe to renumber because the conflict
    # itself stopped this migration ever being applied — `migrate` rejects
    # a multi-leaf graph before applying anything, so no database (staging
    # included) has recorded the old name.
    dependencies = [
        ("bulletins", "0016_uppercase_bulletin_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="weathersnapshot",
            name="snowfall_sum",
            field=models.FloatField(
                blank=True, help_text="Total daily snowfall, in cm.", null=True
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="temperature_2m_max",
            field=models.FloatField(
                blank=True,
                help_text="Maximum daily air temperature at 2m, in °C.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="temperature_2m_min",
            field=models.FloatField(
                blank=True,
                help_text="Minimum daily air temperature at 2m, in °C.",
                null=True,
            ),
        ),
    ]
