# Generated by Django 6.1 on 2026-08-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0018_move_weather_models_to_weather_app"),
        ("core", "0008_requestlog_account_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletinshareclick",
            name="request",
            field=models.ForeignKey(
                help_text="Request context captured when this link was followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulletin_share_clicks",
                to="core.requestlog",
            ),
        ),
    ]
