# Generated by Django 6.0.7 on 2026-07-15 17:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_requestlog_subscriber_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="The client-supplied Idempotency-Key header value. Opaque to the server; typically a uuid4. Unique — a replay hits the same row.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HTTP method of the original request (POST/PATCH/PUT/DELETE).",
                        max_length=16,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Request path of the original request, for diagnostic use.",
                        max_length=2048,
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(
                        help_text="HTTP status code of the cached response."
                    ),
                ),
                (
                    "response_body",
                    models.BinaryField(
                        default=b"",
                        help_text="Raw response body bytes, replayed verbatim on cache hit.",
                    ),
                ),
                (
                    "response_content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Content-Type header of the cached response.",
                        max_length=255,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the cached response stops being served. After this timestamp a replay with the same key re-executes the view.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="core_idempo_expires_9f124d_idx"
                    )
                ],
            },
        ),
    ]
