# Generated by Django 6.0.7 on 2026-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_idempotencyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="body_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="sha256 hex digest of the original request's raw body. Part of the replay fingerprint.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="principal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="str(request.user.pk) of the original requester, or '' for an anonymous request. Server-derived — never taken from client input — so it cannot be spoofed. Part of the replay fingerprint.",
                max_length=64,
            ),
        ),
    ]
