# Generated by Django 6.1 on 2026-08-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_uppercase_geo_match_kind_and_mechanism"),
        ("core", "0007_idempotencyrecord_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated account at request time, if any. Null for anonymous requests (e.g. sign-up before the row exists).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_logs",
                to="accounts.account",
            ),
        ),
    ]
