# Generated by Django 6.0.5 on 2026-05-12 10:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MajorRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="EAWS L1 prefix, e.g. 'CH-4'.",
                        max_length=4,
                        unique=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        help_text="ISO-3166-1 alpha-2 country code, e.g. 'CH'.",
                        max_length=2,
                    ),
                ),
                (
                    "name_native",
                    models.CharField(
                        help_text="Region name in the locally dominant language (German / French / Italian for Switzerland).",
                        max_length=100,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="English name where SLF publishes one; blank otherwise.",
                        max_length=100,
                    ),
                ),
                (
                    "centre",
                    models.JSONField(
                        blank=True,
                        help_text='Derived geographic centre as {"lon": float, "lat": float}. Computed by refresh_eaws_fixtures from the union of L4 children.',
                        null=True,
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        help_text="Derived bounding box as [min_lon, min_lat, max_lon, max_lat]. Computed by refresh_eaws_fixtures from the union of L4 children.",
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        help_text="Derived outer boundary as a GeoJSON Polygon or MultiPolygon. Computed by refresh_eaws_fixtures from the union of L4 children.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "EAWS major region",
                "verbose_name_plural": "EAWS major regions",
                "ordering": ["prefix"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region_id",
                    models.CharField(
                        db_index=True,
                        help_text="SLF region identifier, e.g. 'CH-4115'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "centre",
                    models.JSONField(
                        blank=True,
                        help_text='Geographic centre of the region as {"lon": float, "lat": float}. Stored as JSON; uses WGS 84 coordinates.',
                        null=True,
                    ),
                ),
                (
                    "boundary",
                    models.JSONField(
                        blank=True,
                        help_text='Region boundary as a GeoJSON Polygon geometry object ({"type": "Polygon", "coordinates": [...]}). Stored as JSON rather than a PostGIS geometry type.',
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "EAWS micro-region",
                "verbose_name_plural": "EAWS micro-regions",
                "ordering": ["region_id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroRegionNeighbour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_microregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="regions.microregion",
                    ),
                ),
                (
                    "to_microregion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="regions.microregion",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_microregion", "to_microregion")},
            },
        ),
        migrations.AddField(
            model_name="microregion",
            name="neighbours",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic neighbours — other regions whose polygons share a border with this one. Computed at fixture-build time from the boundary geometry (see scripts/build_regions_fixture.py); not maintained at runtime.",
                through="regions.MicroRegionNeighbour",
                to="regions.microregion",
            ),
        ),
        migrations.CreateModel(
            name="Resort",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternative or marketing name for the resort.",
                        max_length=255,
                    ),
                ),
                (
                    "canton",
                    models.CharField(
                        help_text="Swiss canton abbreviation, e.g. 'VS', 'GR'.",
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "geocode_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("auto", "Auto"),
                            ("import", "Import"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("geocode_confidence", models.FloatField(blank=True, null=True)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("needs_review", models.BooleanField(default=False)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resorts",
                        to="regions.microregion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="EAWS L2 prefix, e.g. 'CH-41'.",
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "name_native",
                    models.CharField(
                        help_text="Region name in the locally dominant language (German / French / Italian for Switzerland).",
                        max_length=100,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="English name where SLF publishes one; blank otherwise.",
                        max_length=100,
                    ),
                ),
                ("centre", models.JSONField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("boundary", models.JSONField(blank=True, null=True)),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subregions",
                        to="regions.majorregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "EAWS sub-region",
                "verbose_name_plural": "EAWS sub-regions",
                "ordering": ["prefix"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="microregion",
            name="subregion",
            field=models.ForeignKey(
                help_text="Parent L2 sub-region. Populated from ``region_id[:5]`` in the fixture.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="regions.subregion",
            ),
        ),
    ]
