# Generated by Django 6.0.5 on 2026-05-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0002_seed_edit_map_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregion",
            name="subregion",
            field=models.ForeignKey(
                help_text="Parent L2 sub-region. Set via the fixture's natural-key list. Swiss rows conventionally share a ``region_id[:5]`` prefix with this sub-region; French rows set the FK explicitly — the slicing convention is Swiss-only and not enforced.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="regions.subregion",
            ),
        ),
    ]
