# Generated by Django 6.0.5 on 2026-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0004_widen_prefix_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregion",
            name="neighbours",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic neighbours — other regions whose polygons share a border with this one. Computed at fixture-build time from the boundary geometry (see build_switzerland_fixture); not maintained at runtime.",
                through="regions.MicroRegionNeighbour",
                to="regions.microregion",
            ),
        ),
    ]
