# Generated by Django 6.0.7 on 2026-07-18 13:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0006_majorregion_display_on_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionAlias",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alias_text",
                    models.CharField(
                        help_text="An alternate name for the region, e.g. a French/German exonym.",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The MicroRegion this alias resolves to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="regions.microregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "region alias",
                "verbose_name_plural": "region aliases",
                "ordering": ["alias_text"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "alias_text"), name="unique_region_alias"
                    )
                ],
            },
        ),
    ]
