# Generated by Django 6.0.7 on 2026-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0009_resort_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="microregion",
            name="basemap_download",
            field=models.JSONField(
                blank=True,
                help_text="Precomputed offline-basemap tile coverage for this region (regions.services.basemap_tiles.MICRO_BAND), populated by `manage.py compute_basemap_download --commit` from a bbox derived from `boundary` (MicroRegion has no stored bbox field). {band, count, mb, over_ceiling, centre_tile, z} — see regions/services/basemap_tiles.py for the shape. Never computed at request time; region geometry is static reference data so this never changes once computed.",
                null=True,
            ),
        ),
    ]
