# Generated by Django 6.0.7 on 2026-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0011_resort_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregion",
            name="basemap_download",
            field=models.JSONField(
                blank=True,
                help_text='Precomputed offline-basemap tile coverage for this region (regions.services.basemap_tiles.MICRO_BAND), populated by `manage.py compute_basemap_download --commit` via basemap_tiles.build_region_blob, which clips the bbox derived from `boundary` (MicroRegion has no stored bbox field) down to the tiles within one margin tile of the real boundary (SNOW-583). {band, count, mb, over_ceiling, centre_tile, z} — `z` is {"<z>": {"<y>": [xmin, xmax]}}, not the rectangular {"<z>": [xmin, xmax, ymin, ymax]} the custom-area download still uses — see regions/services/basemap_tiles.py for the shape. Never computed at request time; region geometry is static reference data so this never changes once computed.',
                null=True,
            ),
        ),
    ]
