# Generated by Django 6.0.7 on 2026-08-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0012_clip_basemap_download_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="why_it_matters",
            field=models.CharField(
                blank=True,
                help_text="One curated sentence on why a backcountry skier should care about this resort — terrain, access, reputation. Not a marketing blurb and not derivable from the numeric columns.",
                max_length=255,
            ),
        ),
    ]
