# Generated by Django 6.0.7 on 2026-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0013_resort_why_it_matters"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="tier",
            field=models.CharField(
                choices=[
                    ("CORE", "Core"),
                    ("STANDARD", "Standard"),
                    ("MINOR", "Minor"),
                ],
                default="STANDARD",
                help_text="How prominently this resort draws on the map. Curated, not derived — CORE is for a resort that carries real avalanche decision-making, which is as often a small high area as a large domain. STANDARD is the default.",
                max_length=20,
            ),
        ),
    ]
