# Generated by Django 6.0.7 on 2026-08-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0014_resort_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="geocode_source",
            field=models.CharField(
                blank=True,
                choices=[("MANUAL", "Manual"), ("AUTO", "Auto"), ("IMPORT", "Import")],
                default="",
                max_length=16,
            ),
        ),
    ]
