# Generated by Django 6.1 on 2026-08-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("regions", "0016_alter_resort_forecast_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="microregion",
            name="centroid_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location at this region's centroid, which the bulletin page reads its forecast through (SNOW-696). Resolved by link_region_centroid_locations from ``centre``. Null until that has run.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="locations.location",
            ),
        ),
    ]
