# Generated by Django 6.1 on 2026-08-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_remove_location_forecast_cell"),
        ("regions", "0018_remove_resort_forecast_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregion",
            name="centroid_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location at this region's centroid, which the bulletin page reads its forecast through (SNOW-696). Resolved by link_region_centroid_locations from ``boundary`` (SNOW-765). Null until that has run.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="locations.location",
            ),
        ),
    ]
