# Generated by Django 6.1 on 2026-08-30 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_remove_location_forecast_cell"),
        ("regions", "0019_alter_microregion_centroid_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="microregion",
            name="centroid_elevation_m",
            field=models.FloatField(
                blank=True,
                help_text="Ground elevation in metres at this region's centroid — the point centre_from_bbox(boundary) resolves to. Fixture data (SNOW-771), resolved once against Open-Meteo by refresh_eaws_fixtures rather than per environment. It is the only part of a centroid that cannot be derived offline, which is why it is stored while the coordinate is not.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="microregion",
            name="centroid_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location at this region's centroid, which the bulletin page reads its forecast through (SNOW-696). Derived, NOT durable: bin/build.sh reloads the EAWS fixtures on every deploy, and a fixture carries no value for this column, so loaddata resets it to NULL every time (SNOW-771). link_region_centroid_locations re-derives it immediately afterwards from ``boundary`` and ``centroid_elevation_m``. Never treat a value here as surviving a deploy.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="locations.location",
            ),
        ),
    ]
