# Generated by Django 6.1.1 on 2026-09-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_location_what3words_and_more"),
        ("regions", "0021_resort_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregion",
            name="centroid_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location at this region's centroid, which the bulletin page reads its forecast through (SNOW-696). Derived, and durable since PR #758: no deploy loads a fixture any more, so nothing NULLs this column. It was wiped on every deploy while build.sh reloaded the EAWS fixtures, because loaddata resets every column a fixture does not carry (SNOW-771). Null on a region an operator has not yet run link_region_centroid_locations against; that command derives it offline from ``boundary`` and ``centroid_elevation_m``.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="locations.location",
            ),
        ),
    ]
