# Generated by Django 6.1.2 on 2026-10-10 15:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0022_centroid_location_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The pass's own name, e.g. Magic Pass.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The key the resort sheet's passes column uses, e.g. magic-pass. Renaming it breaks every sheet row that names it.",
                        unique=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="The pass's own site, where its resort list is published.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "passes",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="resort",
            name="passes",
            field=models.ManyToManyField(
                blank=True,
                help_text="The season passes this resort is sold on (SNOW-1083). A pass only groups resorts — every resort is a place to plan a day whether or not it is on one. Where a pass sells one domain the sheet splits into villages, every village row carries the pass.",
                related_name="resorts",
                to="regions.pass",
            ),
        ),
    ]
