# Generated by Django 6.1.2 on 2026-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0022_centroid_location_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="magic_pass",
            field=models.BooleanField(
                default=False,
                help_text="On the Magic Pass season pass (magicpass.ch). Hand-curated from the pass's resort list (SNOW-1083). Where the pass sells one domain the sheet splits into villages, every village row is flagged.",
            ),
        ),
    ]
