# Generated by Django 6.1 on 2026-08-17 11:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Route label — seeded from the GPX's own name, editable by the owner afterwards.",
                        max_length=100,
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(
                        blank=True,
                        help_text="Name of the uploaded .gpx file. A label only — the file itself is parsed and discarded, never stored.",
                        max_length=255,
                    ),
                ),
                (
                    "points",
                    models.JSONField(
                        help_text="The simplified track as [[lon, lat, ele], …] in GeoJSON axis order. ele is metres, or null where the source had no <ele>."
                    ),
                ),
                (
                    "distance_m",
                    models.FloatField(
                        help_text="Great-circle length of the full-resolution track in metres, derived at ingest before simplification."
                    ),
                ),
                (
                    "ascent_m",
                    models.FloatField(
                        blank=True,
                        help_text="Total positive elevation gain in metres over the full-resolution track. Null — not zero — when the source file carries no elevation data.",
                        null=True,
                    ),
                ),
                (
                    "point_count",
                    models.PositiveIntegerField(
                        help_text="Number of coordinates stored in points."
                    ),
                ),
                (
                    "bounds",
                    models.JSONField(
                        help_text="GeoJSON bbox over the stored points: [min_lon, min_lat, max_lon, max_lat]."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded this route.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
