# Generated by Django 6.1.1 on 2026-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0005_route_slope_samples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="slope_samples",
            field=models.JSONField(
                blank=True,
                help_text="Steepness of the GROUND the track crosses, sampled from the terrain grid at a fixed stride — never derived from the track's own elevation. Null means NEVER SAMPLED, which is not the same fact as a segment whose unknown reason is set (that is ground the survey does not cover); the two must never render alike. Carries a 'summary' key holding the same walk in figures (apps/routes/services/slope_summary.py), written by the sampler and recomputed on read when a record predates it.",
                null=True,
            ),
        ),
    ]
