# Generated by Django 6.1.1 on 2026-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0006_alter_route_slope_samples"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="source_point_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many coordinates the uploaded file carried, before simplification. Null means we did not record it — not zero, and not the same as point_count.",
                null=True,
            ),
        ),
    ]
