# Generated by Django 6.1 on 2026-08-28 16:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadArea",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_id",
                    models.CharField(
                        help_text="The client-minted area id — 'region-<region_id>' or 'custom-<uuid>'. Also names the pinned Cache Storage bucket on each device, which is what makes it the join key.",
                        max_length=100,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("region", "Region"), ("custom", "Custom area")],
                        help_text="Whether this is a whole region or a user-framed area.",
                        max_length=16,
                    ),
                ),
                (
                    "region_id",
                    models.CharField(
                        blank=True,
                        help_text="EAWS micro-region id, for a region area. Blank for a custom area. Not an FK: a region that leaves the fixture should not delete a user's record of having downloaded it.",
                        max_length=50,
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        help_text="[west, south, east, north] in (lon, lat) order, for a custom area. Null for a region, whose tiles are computed server-side from its own boundary.",
                        null=True,
                    ),
                ),
                (
                    "basemap_key",
                    models.CharField(
                        blank=True,
                        help_text="The basemap the area was downloaded under, as the picker keys it. Blank when the client could not resolve one — which reads as an unknown basemap, never a wrong one.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="User-supplied label for a custom area. Blank for a region (whose name is the region's own) and for a custom area the user has never renamed.",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose account this area is recorded against.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "area_id"), name="unique_download_area_per_user"
                    )
                ],
            },
        ),
    ]
