# Generated by Django 6.1 on 2026-08-30 12:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # NOT initial: 0001 is. Django marks a migration initial when the app has
    # no prior model-bearing history, which is true here only because 0006
    # deleted the SNOW-762 estate. Leaving the flag set would make
    # ``migrate --fake-initial`` try to adopt an existing weather_weather
    # table on a database that has genuinely never had one.

    dependencies = [
        ("locations", "0003_remove_location_forecast_cell"),
        ("weather", "0006_delete_weather_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observed_on",
                    models.DateField(
                        db_index=True,
                        help_text="The calendar day this row is OF. Immutable once past — see apps.weather.services.upsert.",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        help_text="When this row was last written (updated on every write)."
                    ),
                ),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(
                        help_text="WMO weather interpretation code (0–99)."
                    ),
                ),
                (
                    "sunrise",
                    models.DateTimeField(
                        help_text="Sunrise, in the location's own local time — the offset the provider returned is preserved rather than normalised to UTC."
                    ),
                ),
                (
                    "sunset",
                    models.DateTimeField(
                        help_text="Sunset, in the location's own local time — the offset the provider returned is preserved rather than normalised to UTC."
                    ),
                ),
                (
                    "temperature_2m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "temperature_2m_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "apparent_temperature_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily apparent (feels-like) temperature, in °C.",
                        null=True,
                    ),
                ),
                (
                    "apparent_temperature_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum daily apparent (feels-like) temperature, in °C.",
                        null=True,
                    ),
                ),
                (
                    "precipitation_sum",
                    models.FloatField(
                        blank=True,
                        help_text="Total daily precipitation (rain + showers + snow), in mm.",
                        null=True,
                    ),
                ),
                (
                    "snowfall_sum",
                    models.FloatField(
                        blank=True, help_text="Total daily snowfall, in cm.", null=True
                    ),
                ),
                (
                    "precipitation_probability_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum daily precipitation probability, as a percentage.",
                        null=True,
                    ),
                ),
                (
                    "precipitation_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Number of hours with measurable precipitation, in hours.",
                        null=True,
                    ),
                ),
                (
                    "wind_speed_10m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily wind speed at 10m, in km/h.",
                        null=True,
                    ),
                ),
                (
                    "wind_gusts_10m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily wind gust speed at 10m, in km/h.",
                        null=True,
                    ),
                ),
                (
                    "wind_direction_10m_dominant",
                    models.FloatField(
                        blank=True,
                        help_text="Dominant daily wind direction at 10m, in degrees (0–360).",
                        null=True,
                    ),
                ),
                (
                    "uv_index_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily UV index (dimensionless).",
                        null=True,
                    ),
                ),
                (
                    "daylight_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Total daylight duration, in seconds.",
                        null=True,
                    ),
                ),
                (
                    "sunshine_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Total sunshine duration, in seconds.",
                        null=True,
                    ),
                ),
                (
                    "freezing_level_height",
                    models.FloatField(
                        blank=True,
                        help_text="Freezing level height in metres, derived as the day's maximum hourly value — Open-Meteo publishes no daily aggregate.",
                        null=True,
                    ),
                ),
                (
                    "hourly",
                    models.JSONField(
                        blank=True,
                        help_text="This day, hour by hour: a list of HourlyRow dicts. Null when the response carried no hourly block. See apps.weather.types.",
                        null=True,
                    ),
                ),
                (
                    "forecast",
                    models.JSONField(
                        blank=True,
                        help_text="The days AFTER observed_on, as known on it: a list of ForecastDay dicts. Only the first few carry a nested 'hourly' key — read it with .get(). See apps.weather.types.",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The location this row describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "weather",
                "ordering": ["-observed_on"],
                "abstract": False,
                "unique_together": {("location", "observed_on")},
            },
        ),
    ]
