# Generated by Django 6.1 on 2026-08-23 13:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0016_alter_resort_forecast_point"),
        ("weather", "0002_move_content_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Curated name, e.g. 'Mont Fort'. Empty for a location minted from a favourite or an observation — naming is a curation act.",
                        max_length=120,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VILLAGE", "Village"),
                            ("MID", "Mid-mountain"),
                            ("PEAK", "Peak"),
                        ],
                        default="",
                        help_text="What sort of place this is. Empty alongside an empty name.",
                        max_length=16,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="Exact WGS-84 latitude. Immovable."),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="Exact WGS-84 longitude. Immovable."),
                ),
                (
                    "elevation_m",
                    models.FloatField(
                        blank=True,
                        help_text="Elevation in metres, resolved once via fetch_elevation. Null until link_location_forecast_cells has run.",
                        null=True,
                    ),
                ),
                (
                    "forecast_cell",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quantised cell at which Open-Meteo is called for this location. Shared with every other location in the cell.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="weather.forecastpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResortLocation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BASE", "Base"),
                            ("MID", "Mid-mountain"),
                            ("TOP", "Top"),
                        ],
                        help_text="What this location is to this resort.",
                        max_length=8,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the resort page leads with this location. Normally the BASE link — the village is where someone arrives.",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="The location, which other resorts may also reference.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resort_locations",
                        to="locations.location",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        help_text="The resort this link belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resort_locations",
                        to="regions.resort",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("resort", "location")},
            },
        ),
    ]
