# Generated by Django 6.1 on 2026-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(
                help_text="Exact WGS-84 latitude. Corrected only here or in the location editor — a correction re-places the same row, it does not make a new place."
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(
                help_text="Exact WGS-84 longitude. Corrected only here or in the location editor — a correction re-places the same row, it does not make a new place."
            ),
        ),
    ]
