# Generated by Django 6.0.5 on 2026-05-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0002_seed_edit_map_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorregion",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="EAWS L1 prefix, e.g. 'CH-4' (CH) or 'AT-07' (EUREGIO).",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="microregion",
            name="subregion",
            field=models.ForeignKey(
                help_text="Parent L2 sub-region. For CH regions, derived from ``region_id[:5]``; for EUREGIO regions (AT, IT) the mapping is set explicitly in the fixture because the prefix length differs.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="regions.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="EAWS L2 prefix, e.g. 'CH-41' (CH) or 'IT-32-BZ' (EUREGIO).",
                max_length=10,
                unique=True,
            ),
        ),
    ]
