"""
regions/migrations/0003_widen_region_prefixes.py — single migration widening prefix fields to their final sizes.

Squashes the two previously separate alterations (0003 + 0004) into one so
that there is no intermediate state where SubRegion.prefix.max_length is 10
(which would reject EUREGIO prefixes such as ``IT-32-BZ-01`` that are 11+
characters).

Final sizes:
  MajorRegion.prefix  max_length=10  (e.g. ``AT-07``)
  SubRegion.prefix    max_length=12  (e.g. ``IT-32-BZ``)
"""

# Generated by Django 6.0.5

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Widen region prefix fields and fix MicroRegion.subregion FK help text."""

    dependencies = [
        ("regions", "0002_seed_edit_map_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorregion",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="EAWS L1 prefix, e.g. 'CH-4' (CH) or 'AT-07' (EUREGIO).",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="microregion",
            name="subregion",
            field=models.ForeignKey(
                help_text="Parent L2 sub-region. For CH regions, derived from ``region_id[:5]``; for EUREGIO regions (AT, IT) the mapping is set explicitly in the fixture because the prefix length differs.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="micro_regions",
                to="regions.subregion",
            ),
        ),
        migrations.AlterField(
            model_name="subregion",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="EAWS L2 prefix, e.g. 'CH-41' (CH) or 'IT-32-BZ' (EUREGIO).",
                max_length=12,
                unique=True,
            ),
        ),
    ]
