# Generated by Django 6.0.5 on 2026-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "regions",
            "0003_alter_majorregion_prefix_alter_microregion_subregion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subregion",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text="EAWS L2 prefix, e.g. 'CH-41' (CH) or 'IT-32-BZ' (EUREGIO).",
                max_length=12,
                unique=True,
            ),
        ),
    ]
