# Generated by Django 6.0.5 on 2026-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0005_update_neighbours_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorregion",
            name="display_on_map",
            field=models.BooleanField(
                default=True,
                help_text="Whether this major region appears on the public map. Set to False to hide it from the L1/L2/L4 GeoJSON endpoints while keeping bulletin pages accessible at their canonical URLs.",
            ),
        ),
    ]
