# Generated by Django 6.0.7 on 2026-07-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0011_alter_bulletin_render_model"),
        ("regions", "0007_regionalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="forecast_point",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared weather-sampling point; resolved once from lat/lon.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resorts",
                to="bulletins.forecastpoint",
            ),
        ),
    ]
