# Generated by Django 6.0.7 on 2026-07-24 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0008_resort_forecast_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="base_elevation_m",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Base elevation in metres.", null=True
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="num_lifts",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of lifts.", null=True
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="num_runs",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of piste runs.", null=True
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="operator_name",
            field=models.CharField(
                blank=True,
                help_text="Operating company name, hand-curated (not from any feed).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="top_elevation_m",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Top elevation in metres.", null=True
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="total_piste_km",
            field=models.FloatField(
                blank=True, help_text="Total piste length in kilometres.", null=True
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="typical_season_close",
            field=models.CharField(
                blank=True,
                help_text="Typical season closing as month-day, e.g. 04-30.",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
                        "Enter a month-day as MM-DD, e.g. 12-01.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="typical_season_open",
            field=models.CharField(
                blank=True,
                help_text="Typical season opening as month-day, e.g. 12-01.",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
                        "Enter a month-day as MM-DD, e.g. 12-01.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Official resort website, hand-curated (not from any feed).",
            ),
        ),
    ]
