# Generated by Django 6.0.7 on 2026-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0010_add_basemap_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="kind",
            field=models.CharField(
                choices=[
                    ("RESORT", "Ski resort"),
                    ("TOURING_TERRAIN", "Touring terrain"),
                ],
                default="RESORT",
                help_text="RESORT for a lift-served ski area; TOURING_TERRAIN for avalanche terrain with no lifts, which is kept for its bulletin relevance but excluded from every resort surface.",
                max_length=20,
            ),
        ),
    ]
