# Generated by Django 5.2.13 on 2026-05-01 21:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0001_initial"),
        ("pipeline", "0017_remove_bulletin_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was last written (updated on every upsert).",
                    ),
                ),
                (
                    "valid_for_date",
                    models.DateField(
                        db_index=True,
                        help_text="The calendar date this weather observation/forecast applies to.",
                    ),
                ),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(
                        help_text="WMO weather interpretation code (0–99)."
                    ),
                ),
                (
                    "sunrise",
                    models.DateTimeField(
                        help_text="Sunrise time for this region on valid_for_date (tz-aware, local time)."
                    ),
                ),
                (
                    "sunset",
                    models.DateTimeField(
                        help_text="Sunset time for this region on valid_for_date (tz-aware, local time)."
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="pipeline.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_for_date", "region__region_id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["region", "valid_for_date"],
                        name="bulletins_w_region__26008e_idx",
                    )
                ],
                "unique_together": {("region", "valid_for_date")},
            },
        ),
    ]
