# Generated by Django 6.0.5 on 2026-05-20 21:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0001_initial"),
        ("regions", "0006_majorregion_display_on_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinShare",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="URL-safe random token used in the /s/<token>/ short URL.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="The calendar date the sharer was viewing."
                    ),
                ),
                (
                    "bulletin",
                    models.ForeignKey(
                        blank=True,
                        help_text="The bulletin that was active when this share was created. Nulled when the bulletin is deleted; the share row is preserved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="bulletins.bulletin",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The region the sharer was viewing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletin_shares",
                        to="regions.microregion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BulletinShareClick",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address (REMOTE_ADDR or first X-Forwarded-For element).",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTTP_USER_AGENT from the click request.",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Session key at click time (empty when no session exists).",
                        max_length=64,
                    ),
                ),
                (
                    "referer",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="HTTP Referer header at click time.",
                    ),
                ),
                (
                    "sec_purpose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sec-Purpose header value (e.g. 'prefetch') for speculative-load detection. Empty on regular navigations.",
                        max_length=64,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code resolved from ip_address via GeoIP. Empty when the lookup fails or the IP is private.",
                        max_length=2,
                    ),
                ),
                (
                    "visitor_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="First 16 hex chars of sha256(ip + '|' + ua). Pseudonymous cross-visit identifier; not reversible without the original IP.",
                        max_length=16,
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        help_text="The share link that was followed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="bulletins.bulletinshare",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
