# Generated by Django 6.0.6 on 2026-06-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0005_regiondayrating_source_bands"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="pdf_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the source bulletin PDF (SLF / ALBINA / Météo-France). Populated by upsert_bulletin at ingest time and back-filled by the backfill_pdf_urls management command.",
                max_length=500,
            ),
        ),
    ]
