# Generated by Django 6.0.7 on 2026-07-18 20:01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0008_forecastpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastPointWeather",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this row was last written (updated on every upsert).",
                    ),
                ),
                (
                    "valid_for_date",
                    models.DateField(
                        db_index=True,
                        help_text="The calendar date this weather forecast applies to.",
                    ),
                ),
                (
                    "weather_code",
                    models.PositiveSmallIntegerField(
                        help_text="WMO weather interpretation code (0–99)."
                    ),
                ),
                (
                    "sunrise",
                    models.DateTimeField(
                        help_text="Sunrise time for this point on valid_for_date (tz-aware, local time)."
                    ),
                ),
                (
                    "sunset",
                    models.DateTimeField(
                        help_text="Sunset time for this point on valid_for_date (tz-aware, local time)."
                    ),
                ),
                (
                    "temperature_2m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "temperature_2m_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum daily air temperature at 2m, in °C.",
                        null=True,
                    ),
                ),
                (
                    "apparent_temperature_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily apparent (feels-like) temperature, in °C.",
                        null=True,
                    ),
                ),
                (
                    "apparent_temperature_min",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum daily apparent (feels-like) temperature, in °C.",
                        null=True,
                    ),
                ),
                (
                    "precipitation_sum",
                    models.FloatField(
                        blank=True,
                        help_text="Total daily precipitation (rain + showers + snow), in mm.",
                        null=True,
                    ),
                ),
                (
                    "snowfall_sum",
                    models.FloatField(
                        blank=True, help_text="Total daily snowfall, in cm.", null=True
                    ),
                ),
                (
                    "precipitation_probability_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum daily precipitation probability, as a percentage.",
                        null=True,
                    ),
                ),
                (
                    "precipitation_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Number of hours with measurable precipitation, in hours.",
                        null=True,
                    ),
                ),
                (
                    "wind_speed_10m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily wind speed at 10m, in km/h.",
                        null=True,
                    ),
                ),
                (
                    "wind_gusts_10m_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily wind gust speed at 10m, in km/h.",
                        null=True,
                    ),
                ),
                (
                    "wind_direction_10m_dominant",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Dominant daily wind direction at 10m, in degrees (0–360).",
                        null=True,
                    ),
                ),
                (
                    "uv_index_max",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum daily UV index (dimensionless).",
                        null=True,
                    ),
                ),
                (
                    "daylight_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Total daylight duration, in seconds.",
                        null=True,
                    ),
                ),
                (
                    "sunshine_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Total sunshine duration, in seconds.",
                        null=True,
                    ),
                ),
                (
                    "forecast_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="bulletins.forecastpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_for_date", "forecast_point__id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["forecast_point", "valid_for_date"],
                        name="bulletins_f_forecas_e18a91_idx",
                    )
                ],
                "unique_together": {("forecast_point", "valid_for_date")},
            },
        ),
    ]
