# Generated by Django 6.0.7 on 2026-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0010_forecastpointweather_freezing_level_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="render_model",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Versioned, presentation-ready view of the bulletin built from raw_data. Shape: {version, source, danger, traits, metadata, prose, danger_patterns} — see docs/render-model.md. Rebuilt by upsert_bulletin and on demand by rebuild_render_models.",
            ),
        ),
    ]
