# Generated by Django 6.0.7 on 2026-07-20 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulletins", "0010_forecastpointweather_freezing_level_height_and_more"),
        ("favourites", "0002_seed_favourites_flag"),
        ("regions", "0007_regionalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="favourite_latitude_within_wgs84",
            ),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="favourite_longitude_within_wgs84",
            ),
        ),
    ]
