# Generated by Django 6.1 on 2026-08-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0005_alter_favourite_forecast_point"),
        ("locations", "0001_initial"),
        ("weather", "0002_move_content_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location this pin is. Reaches coordinates, elevation and weather. Null only for a row the SNOW-704 backfill has not reached yet.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="favourites",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="elevation",
            field=models.FloatField(
                help_text="Elevation in metres. Superseded by location.elevation_m (SNOW-704); dropped once nothing reads it."
            ),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="forecast_point",
            field=models.ForeignKey(
                help_text="Shared ForecastPoint this pin's coordinates resolved to. Superseded by location.forecast_cell (SNOW-704); dropped once nothing reads it.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="favourites",
                to="weather.forecastpoint",
            ),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="latitude",
            field=models.FloatField(
                help_text="WGS-84 latitude of the saved pin. Superseded by location.latitude (SNOW-704); dropped once nothing reads it."
            ),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="longitude",
            field=models.FloatField(
                help_text="WGS-84 longitude of the saved pin. Superseded by location.longitude (SNOW-704); dropped once nothing reads it."
            ),
        ),
    ]
