# Generated by Django 6.0.6 on 2026-06-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0006_majorregion_display_on_map"),
        ("subscriptions", "0002_create_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="geo_match_kind",
            field=models.CharField(
                choices=[
                    ("in_region", "In region"),
                    ("in_neighbour", "In neighbouring region"),
                    ("elsewhere", "Elsewhere"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text="How the subscriber's geolocation (from subscribed_via) relates to the subscribed region at sign-up time. Frozen on INSERT; never updated. Raw geo fields live on subscribed_via (RequestLog).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="geo_matched_region",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific MicroRegion the subscriber's geolocation fell inside (target region itself, or the first matching neighbour). Null when geo_match_kind is elsewhere or unknown. Analytics-only; not surfaced on the public region API.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="regions.microregion",
            ),
        ),
    ]
