# Generated by Django 6.0.6 on 2026-06-11 17:14
#
# SNOW-312: The EncryptedEmailField class (subscriptions.fields) was deleted
# as part of the encryption rollback.  The original operation altered the
# email column to a text type via EncryptedEmailField.get_internal_type()
# returning "TextField".  That is DDL-identical to models.TextField(unique=True,
# db_index=True), so the stub below keeps the migration graph importable on a
# fresh install and produces identical schema to the original.  Applied
# databases never re-read migration content; this edit is safe for production.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_subscriber_subscription_request_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
