# Generated by Django 6.0.6 on 2026-06-11 17:14

from django.db import migrations

import subscriptions.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_subscriber_subscription_request_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=subscriptions.fields.EncryptedEmailField(
                db_index=True, max_length=254, unique=True
            ),
        ),
    ]
