# Generated by Django 6.0.5 on 2026-05-11 12:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_rename_region_fk_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credential_id", models.TextField(unique=True)),
                ("public_key", models.BinaryField()),
                ("sign_count", models.PositiveIntegerField(default=0)),
                (
                    "aaguid",
                    models.UUIDField(
                        blank=True,
                        help_text="Passkey provider identifier — reserved for future AAGUID display-name lookup.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label shown on the manage page (auto-generated).",
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        help_text='"platform" or "cross-platform".', max_length=32
                    ),
                ),
                (
                    "backed_up",
                    models.BooleanField(
                        default=False,
                        help_text="True when the passkey is synced to the cloud (e.g. iCloud Keychain).",
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to="subscriptions.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
