# Generated by Django 6.0.5 on 2026-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_passkey_credential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passkeycredential",
            name="aaguid",
            field=models.UUIDField(
                blank=True,
                help_text="Reserved for future AAGUID provider name lookup.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="passkeycredential",
            name="backed_up",
            field=models.BooleanField(
                default=False, help_text="True when the passkey is synced to the cloud."
            ),
        ),
    ]
