# Generated by Django 6.0.6 on 2026-06-19 16:53

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0006_majorregion_display_on_map"),
        ("accounts", "0003_geo_match_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldObservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.FloatField(
                        help_text="WGS-84 latitude of the GPS fix at report time."
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="WGS-84 longitude of the GPS fix at report time."
                    ),
                ),
                (
                    "accuracy_radius_km",
                    models.FloatField(
                        blank=True,
                        help_text="Browser-reported GPS accuracy radius in kilometres (converted from metres at the view layer).",
                        null=True,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Wall-clock time when the report was submitted.",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("WHUMPFING", "Whumpfing"),
                            ("PINWHEELS", "Pinwheels"),
                            ("WIND_STRIATIONS", "Wind striations"),
                            ("FRACTURES", "Fractures"),
                            ("SHOOTING_CRACKS", "Shooting cracks"),
                        ],
                        help_text="Single OBSERVATION_TYPE value reported by the subscriber (e.g. WHUMPFING).  To report two problems, submit two reports.",
                        max_length=32,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Best-effort MicroRegion resolved from the GPS fix. Null when the point cannot be matched to a known boundary.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="regions.microregion",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        help_text="Subscriber who submitted this report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_observations",
                        to="accounts.subscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "abstract": False,
            },
        ),
    ]
