# Generated by Django 6.0.7 on 2026-07-20 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0006_seed_community_reports_flag"),
        ("regions", "0007_regionalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="fieldobservation_latitude_within_wgs84",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="fieldobservation_longitude_within_wgs84",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gps_latitude__isnull", True),
                    models.Q(("gps_latitude__gte", -90), ("gps_latitude__lte", 90)),
                    _connector="OR",
                ),
                name="fieldobservation_gps_latitude_within_wgs84",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gps_longitude__isnull", True),
                    models.Q(("gps_longitude__gte", -180), ("gps_longitude__lte", 180)),
                    _connector="OR",
                ),
                name="fieldobservation_gps_longitude_within_wgs84",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("accuracy_radius_km__isnull", True),
                    ("accuracy_radius_km__gte", 0),
                    _connector="OR",
                ),
                name="fieldobservation_accuracy_radius_km_non_negative",
            ),
        ),
    ]
