# Generated by Django 6.1 on 2026-08-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("observations", "0008_seed_observations_page_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldobservation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this observation happened. Shared with any other observation at the same point. Null only for a row the SNOW-709 backfill has not reached yet.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="field_observations",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="fieldobservation",
            name="latitude",
            field=models.FloatField(
                help_text="WGS-84 latitude of the report location (GPS fix, refined pin, or manually-placed pin). Superseded by location.latitude."
            ),
        ),
        migrations.AlterField(
            model_name="fieldobservation",
            name="longitude",
            field=models.FloatField(
                help_text="WGS-84 longitude of the report location (GPS fix, refined pin, or manually-placed pin). Superseded by location.longitude."
            ),
        ),
    ]
