# Generated by Django 6.1.1 on 2026-09-26 10:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_id",
                    models.CharField(
                        help_text="The identifier the client presents: a random string for a DCR client, the metadata document URL for a CIMD client.",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DCR", "Dynamic registration"),
                            ("CIMD", "Client ID metadata document"),
                            ("LOCAL", "Local (mint_mcp_token)"),
                        ],
                        help_text="How the client registered.",
                        max_length=16,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="The name the client gave itself, shown on the consent page.",
                        max_length=100,
                    ),
                ),
                (
                    "redirect_uris",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The redirect URIs the authorize endpoint accepts.",
                    ),
                ),
                (
                    "metadata_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a CIMD client's metadata document was last fetched.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth client",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OAuthGrant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Space-separated scopes the user approved.",
                        max_length=200,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        blank=True,
                        help_text="The MCP resource URL the approval was for.",
                        max_length=500,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a token under this grant last reached the MCP server.",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user disconnected the client; null while active.",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client the user approved.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="oauth.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who approved the client.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth grant",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the code. The code itself is not stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uri",
                    models.CharField(
                        help_text="The redirect URI the authorize request named.",
                        max_length=500,
                    ),
                ),
                (
                    "code_challenge",
                    models.CharField(
                        help_text="The S256 PKCE challenge the authorize request carried.",
                        max_length=128,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="The MCP resource URL the code is for.",
                        max_length=500,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Space-separated scopes the code carries.",
                        max_length=200,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the code stops being accepted."
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the code was exchanged; a used code is never accepted again.",
                        null=True,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        help_text="The grant the code was issued under.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="oauth.oauthgrant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Access token"),
                            ("REFRESH", "Refresh token"),
                        ],
                        help_text="Access or refresh.",
                        max_length=16,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the token. The token itself is not stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="The MCP resource URL the token is for (its audience).",
                        max_length=500,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Space-separated scopes the token carries.",
                        max_length=200,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the token stops being accepted."
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token was revoked; null while live.",
                        null=True,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        help_text="The grant the token was issued under.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="oauth.oauthgrant",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="For a rotated refresh token, the token that replaced it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="oauth.oauthtoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth token",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="oauthgrant",
            constraint=models.UniqueConstraint(
                fields=("user", "client"), name="unique_oauth_grant_per_user_client"
            ),
        ),
    ]
