# Generated by Django 6.1.1 on 2026-09-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="For a refresh token, when it was spent on a refresh. Presenting it again is reuse, whether or not a successor was issued.",
                null=True,
            ),
        ),
    ]
